/* empty css                      */import{S as l,A as c}from"./assets/vendor-HTdmVadK.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();new l(".my-swiper",{modules:[c],loop:!0,speed:6e3,allowTouchMove:!1,grabCursor:!1,slidesPerView:1.2,spaceBetween:16,autoplay:{delay:0,disableOnInteraction:!1,pauseOnMouseEnter:!1},breakpoints:{1440:{slidesPerView:2.4,spaceBetween:24}}});document.querySelectorAll(".faq-acc-el-trigger").forEach(i=>{i.addEventListener("click",()=>{const o=i.closest(".faq-acc-el"),r=o.querySelector(".faq-acc-el-descr-frame"),s=i.querySelector("svg"),e=o.classList.contains("open"),t=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M24 12L14 22L4 12" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M24 6L14 16L4 6" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,n=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M24 16L14 6L4 16" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M24 22L14 12L4 22" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;e?(o.classList.remove("open"),r.style.maxHeight="0",s.outerHTML=t):(o.classList.add("open"),r.style.maxHeight=r.scrollHeight+"px",s.outerHTML=n)})});
//# sourceMappingURL=index.js.map
